version: '3.8'

volumes:
  pg_data:
  static_value:


services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}-backend:latest
    env_file: .env
    volumes:
      - static_value:/static/
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: ${DOCKERHUB_USERNAME}/nginx:latest
    ports:
      - "8000:80"
    volumes:
      - static_value:/app/static/
    depends_on:
      - backend
    restart: unless-stopped
