version: '3'

volumes:
  pg_data:
  static_value:


services:
  db:
    image: postgres:16.2-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_value:/static/
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend
