version: '3'

volumes:
  pg_data:
  static_value:


services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}-backend
    env_file: .env
    volumes:
      - static_value:/static/
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend
