# docker-compose.production.yml

volumes:
  pg_data:
  static_value:


services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    image: dockerhub4u/dv-backend-backend:latest
    env_file: .env
    volumes:
      - static_value:/app/static
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - static_value:/static
      - /home/dv-backend/infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
