# Generated by Django 4.2.7 on 2024-06-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Альтернативное название'),
        ),
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страны'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность фильма (минуты)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.JSONField(blank=True, null=True, verbose_name='Персоны'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=None, null=True, upload_to='movies/posters/', verbose_name='Ссылка на изображение'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_imdb',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг IMDb'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_kp',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг Кинопоиск'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.DeleteModel(
            name='GenreMovie',
        ),
    ]
