# Generated by Django 4.2.7 on 2024-05-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_user_rename_genretitle_genremovie_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
