# Generated by Django 4.2.7 on 2024-06-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreMovie',
        ),
    ]
