# Generated by Django 4.2.7 on 2024-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Колекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название коллекции'),
        ),
        migrations.AddField(
            model_name='movie',
            name='collections',
            field=models.ManyToManyField(blank=True, to='movies.collection', verbose_name='Коллекция'),
        ),
    ]
