# Generated by Django 4.2.7 on 2024-05-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='movies/images/', verbose_name='Ссылка на изображение'),
        ),
    ]
