# Generated by Django 4.2.7 on 2024-06-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_collection_alter_genre_name_movie_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',), 'verbose_name': 'Подборка', 'verbose_name_plural': 'Подборка'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='collections/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название подборки'),
        ),
    ]
