# Generated by Django 4.2.7 on 2024-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_image_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=None, null=True, upload_to='movies/posters/', verbose_name='Ссылка на изображение'),
        ),
    ]
