# Generated by Django 4.2.7 on 2024-06-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_collection_options_remove_movie_collections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.AddField(
            model_name='collection',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='collections/', verbose_name='Ссылка на изображение'),
        ),
    ]
