# Generated by Django 4.2.7 on 2024-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='votes_imdb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голоса IMDb'),
        ),
        migrations.AddField(
            model_name='movie',
            name='votes_kp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голоса Кинопоиск'),
        ),
    ]
