# Generated by Django 4.2.7 on 2024-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('voting', 'Голосование'), ('closed', 'Закрыто')], default='draft', max_length=10)),
                ('movies', models.ManyToManyField(to='movies.movie', verbose_name='Фильм')),
                ('users', models.ManyToManyField(to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ('date',),
            },
        ),
    ]
