# Generated by Django 4.2.7 on 2024-04-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name': 'CustomSession',
                'verbose_name_plural': 'CustomSessions',
            },
        ),
    ]
