# Generated by Django 4.2.7 on 2024-05-16 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0002_user_password'),
        ('custom_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovieVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_sessions.customsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'ordering': ('movie',),
            },
        ),
    ]
