# Generated by Django 4.2.7 on 2024-05-28 19:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sessions', '0002_usermovievote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор сессии'),
        ),
    ]
