# Generated by Django 4.2.7 on 2024-05-28 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sessions', '0003_alter_customsession_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор сессии'),
        ),
    ]
