# Generated by Django 4.2.7 on 2024-05-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sessions', '0003_user_delete_room_alter_customsession_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
