# Generated by Django 4.2.7 on 2024-05-28 19:41

import custom_sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sessions', '0004_alter_customsession_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='id',
            field=models.CharField(default=custom_sessions.models.generate_id, editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор сессии'),
        ),
    ]
