# Generated by Django 4.2.7 on 2024-05-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('custom_sessions', '0005_alter_customsession_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsession',
            options={'default_related_name': 'custom_sessions', 'ordering': ('date',), 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AddField(
            model_name='customsession',
            name='matched_movies',
            field=models.ManyToManyField(related_name='matched_sessions', to='movies.movie', verbose_name='Фильм'),
        ),
        migrations.DeleteModel(
            name='UserMovieVote',
        ),
    ]
