# Generated by Django 4.2.7 on 2024-06-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('custom_sessions', '0006_alter_customsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='matched_movies',
            field=models.ManyToManyField(blank=True, related_name='matched_movies_custom_sessions', to='movies.movie', verbose_name='Избранный фильм'),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.movie', verbose_name='Фильм'),
        ),
    ]
