# Generated by Django 4.2.11 on 2024-05-10 14:09

from django.db import migrations, models
import services.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, validators=[services.validators.validate_name], verbose_name='Имя')),
                ('device_id', models.CharField(max_length=24, unique=True, verbose_name='ID устройства')),
            ],
        ),
    ]
