# .github/workflows/main.yml
name: dv_backend main workflow

on:
  push:
    branches:
      # - '**'
      - develop-patch-1

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8 isort
    - name: Test with flake8
      run: |
        python -m flake8
    - name: Auto-correct imports
      # isort --atomic only apply changes if they don't introduce syntax errors
      run: isort --atomic .
    # Commit all changed files back to the repository
    - name: Commit and push auto corrections
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # Leave original message for automatic corrections
        commit_message: "${{ github.event.head_commit.message }}"

  build_and_push_to_docker_hub:
    name: Push Docker images to DockerHub
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check environment variables
        run: |
          echo "DOCKER_USERNAME is ${{ secrets.DOCKER_USERNAME }}"

      - name: Build and push Backend image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dv-backend-backend:latest
      - name: Build and push Nginx image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./infra
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dv-backend-nginx:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build_and_push_to_docker_hub
      # - build_gateway_and_push_to_docker_hub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy docker-compose.yml via ssh
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "docker-compose.production.yml"
          target: "dv-backend/"
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd dv-backend
            sudo docker compose -f docker-compose.production.yml pull
            sudo docker compose -f docker-compose.production.yml down
            sudo docker compose -f docker-compose.production.yml up -d
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic --noinput
            sudo docker compose -f docker-compose.production.yml exec backend cp -r /app/static/. /static_backend/static/
  